# Generated by Django 4.1.3 on 2023-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_regform_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/usere'),
        ),
    ]
