# Generated by Django 4.1.3 on 2022-12-05 15:30

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='e_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
